[FEAT] AnswerDetailViewController MVVM-C(Combine) + Adaptor Pattern 적용
Team-Plu/Plu-iOS pull request #72
Opened 2023-12-21 17:00 UTC by cchanmi

## [FEAT] AnswerDetailViewController MVVM-C(Combine) + Adaptor Pattern 적용

## 🌱 작업한 내용

## 공감 버튼 관련 로직

|    설명   |   스크린샷   |
| :-------------: | :----------: |
| 공감 버튼 클릭하지 않았을 때 | <img width="311" alt="image" src="https://github.com/Team-Plu/Plu-iOS/assets/86944161/939f3bcf-14e9-41a6-a25d-021f6aa09327">|
| 공감 버튼 클릭했을 때 | <img width="302" alt="image" src="https://github.com/Team-Plu/Plu-iOS/assets/86944161/973aa061-88ed-4d4c-b675-c5ae330db5b2">|

공감 버튼이 선택되어 있지 않을 때에는 공감수를 올려 주어야 하고, 공감 버튼이 선택되어 있을 때 버튼 클릭시 공감수를 내려 주어야 하기 때문에, up, down case를 가지는 CountType enum을 하나 만들었어요.
```swift
enum CountType {
    case up, down
}
```

ViewController에서 공감 버튼 클릭시 공감수, 버튼 상태값과 함께 CountType의 type도 같이 보냅니다.
```swift
sympathyButton.tapPublisher
    .sink { [weak self] _ in
        guard let self else { return }
         let countType = empathyState ? CountType.down : CountType.up
         self.empathyButtonTappedSubject.send((EmpthyCountRequest(empthyState: empathyState,
                                                                  empthyCount: empathyCount), countType))
    }
    .store(in: &cancleBag)
```

ViewModel에서 해당 type을 통해 count+1 또는 count-1을 해 주고, 버튼의 상태값을 논리 부정 연산자를 사용해 반대값을 서버 통신할 Request 구조체에 담아 return해 줍니다. 현재는 공감 버튼 서버 통신 후, 해당 버튼의 상태값보다는 서버에서 서버 통신을 성공했음을 알리는 responser가 올 거라고 가정하고 코드를 작성했기 때문에, 이전에 mapping으로 가공한 값을 promise로 담아서 return 해 주었어요.

```swift
let empathyButtonResult = input.empathyButtonTappedSubject
    .map { (request, type) -> EmpthyCountRequest in
        switch type {
        case .up:
            return EmpthyCountRequest(empthyState: !request.empthyState,
                                      empthyCount: request.empthyCount+1)
        case .down:
            return EmpthyCountRequest(empthyState: !request.empthyState,
                                      empthyCount: request.empthyCount-1)
        }
    }
    .flatMap { request -> AnyPublisher<EmpthyCountResponse, Never> in
        return Future<EmpthyCountResponse, Error> { promise in
            Task {
                do {
                    try await self.manager.empthyStateReqeust(request: request)
                    promise(.success((EmpthyCountResponse(empthyState: request.empthyState,
                                                          empthyCount: request.empthyCount))))
                } catch {
                    promise(.failure(error))
                }
            }
        }
        .catch { _ in
            Just(EmpthyCountResponse(empthyState: false, empthyCount: 0))
        }
        .eraseToAnyPublisher()
    }
    .eraseToAnyPublisher()
```

## 🌱 PR Point

- 처음에는 count+1, -1이나 버튼 상태값을 바꿔 주는 것도 ViewController에서 했었는데, ViewController는 단순히 Input이 들어오면 ViewModel에게 알려 주고, output을 받으면 바인딩을 해 주는 역할에 집중하는 게 좋겠다고 생각하여서 해당 로직들을 ViewModel로 옮기게 되었어요.

## 📸 스크린샷
![Simulator Screen Recording - iPhone 13 mini - 2023-12-22 at 01 55 03](https://github.com/Team-Plu/Plu-iOS/assets/86944161/61269b0d-703a-4db3-a9b1-a4ee1a25ac70)

## 📮 관련 이슈

- Resolved: #70

2023-12-22 02:50 UTC, kimscastle approved these changes
수고하셨습니다 pr에 맨 아래 스크린샷에 표가 없길래 넣어놨습니다!

2023-12-22 03:49 UTC, kimscastle reviewed
제가 코드를 잘 이해하지 못해서일수도있는데
viewcontroller가 데이터를 들고있는 부분이있어서 확인 부탁드립니다

2023-12-22 03:49 UTC, kimscastle commented on Plu-iOS/Plu-iOS/Scenes/AnswerDetail/Type/EmpathyType.swift
> +enum EmpathyType {
이거 global enum에 Element에 똑같은게 있습니다~
필요한게 있다면 해당 파일에서 추가해서 쓰는게 좋을거같아요

2023-12-22 03:49 UTC, kimscastle commented on Plu-iOS/Plu-iOS/Scenes/AnswerDetail/ViewController/AnswerDetailViewController.swift
> +    private var empathyType = EmpathyType.air
viewController에서 data를 들고있는 방식이 어색하다고 느껴지네요
해당 데이터가 왜 viewcontroller에 있는걸까요?

2023-12-22 03:49 UTC, kimscastle commented on Plu-iOS/Plu-iOS/Scenes/AnswerDetail/ViewController/AnswerDetailViewController.swift
> +                self.empathyType = response.empathyType
viewmodel이 해당 data를 가지고 업데이트 시켜야하는게 자연스러워보이긴합니다

2023-12-22 07:20 UTC, ffalswo2 requested changes
수고하셨습니다!

2023-12-22 07:20 UTC, ffalswo2 commented on Plu-iOS/Plu-iOS/Scenes/AnswerDetail/ViewModel/AnswerDetailViewModelImpl.swift
> +                                              empthyCount: request.empthyCount+1)
+1, -1 같은 값도 위에 enum에서 addValue등으로 case와 같이 정의하면 좋을 것 같습니다. 그러면 사용할 때 switch문을 안쓰고 아래와 같이 한줄로 작성할 수 있을 것 같네요
```swift
EmpthyCountRequest(empthyState: !request.empthyState,
                                              empthyCount: request.empthyCount+ type.addValue)
```

2023-12-22 07:20 UTC, ffalswo2 commented on Plu-iOS/Plu-iOS/Scenes/AnswerDetail/ViewModel/AnswerDetailViewModelImpl.swift
> +                self.adaptor.pop()
sink 구조체에 저장되는 클로저가 해당 ViewModel를 캡쳐하기 때문에 `[weak self]`를 써주지 않으면 순환참조가 생길 수 있어 추가 부탁드립니다.
`ViewModelImpl -> cancelBag -> Sink -> closure -> ViewModelImpl ...`

2023-12-22 07:23 UTC, ffalswo2 commented on Plu-iOS/Plu-iOS/Scenes/AnswerDetail/ViewController/AnswerDetailViewController.swift
> +    private var empathyType = EmpathyType.air
저도 이 데이터들은 Viewmodel에 있어야한다고 생각합니다

2023-12-22 11:38 UTC, cchanmi commented on Plu-iOS/Plu-iOS/Scenes/AnswerDetail/ViewController/AnswerDetailViewController.swift
> +    private var empathyType = EmpathyType.air
처음에 ViewWillAppear에서 답변에 대한 데이터들을 받고, 이후에 버튼 클릭시의 상태값들을 반영해 주기 위해서 저장값이 필요하다고 생각을 하여서 이렇게 작성하게 되었는데
다시 잘 생각해 보니 VC가 어떠한 데이터를 가공할 필요도 없지만, 그거랑 같은 의미로 데이터를 들고 있을 필요도 없겠네요 ... 수정하겠숩니다 😞
@ffalswo2 @kimscastle

2023-12-22 11:39 UTC, cchanmi commented on Plu-iOS/Plu-iOS/Scenes/AnswerDetail/ViewModel/AnswerDetailViewModelImpl.swift
> +                                              empthyCount: request.empthyCount+1)
이 부분 코드가 깔끔하지 않은 느낌이었는데 좋은 방법인 것 같아요!
반영하겠숩니다 😞

2023-12-24 09:13 UTC, cchanmi commented on Plu-iOS/Plu-iOS/Scenes/AnswerDetail/Type/EmpathyType.swift
> +enum EmpathyType {
[00c43a3](https://github.com/Team-Plu/Plu-iOS/pull/72/commits/00c43a39a18ccfe6ea7d7af49ad99944825220d2) 반영했습니다
@kimscastle

2023-12-24 09:14 UTC, cchanmi commented on Plu-iOS/Plu-iOS/Scenes/AnswerDetail/ViewController/AnswerDetailViewController.swift
> +    private var empathyType = EmpathyType.air
[544fe0a](https://github.com/Team-Plu/Plu-iOS/pull/72/commits/544fe0a42331883dc9082b6c8474c60d99b7531d)
반영했습니다
@kimscastle @ffalswo2

2023-12-24 09:14 UTC, cchanmi commented on Plu-iOS/Plu-iOS/Scenes/AnswerDetail/ViewModel/AnswerDetailViewModelImpl.swift
> +                                              empthyCount: request.empthyCount+1)
[3483926](https://github.com/Team-Plu/Plu-iOS/pull/72/commits/348392664d1809537aea2157c905e346f1d8e8a0)
밑에 weak self랑 같이 반영한 커밋입니다 @ffalswo2

2023-12-24 09:48 UTC, kimscastle approved these changes
고생했습니다~
민재가 확인다하면 머지하시죠~

2023-12-26 06:39 UTC, ffalswo2 approved these changes
수고하셨습니다!

2024-01-01 01:49 UTC, merged